import { Octokit } from "@octokit/rest";
import type { RunReport, CaseResult } from "@qatool/core";
import "dotenv/config";

export interface GitHubIntegrationOptions {
  token?: string;
  repo?: string; // Format: "owner/repo" or separate owner/repo
  owner?: string;
  tagsFilter?: string[];
}

export interface GitHubSyncResult {
  totalFailures: number;
  syncedCount: number;
  createdCount: number;
  commentedCount: number;
  issues: Array<{
    testId: string;
    issueNumber: number;
    issueUrl: string;
    action: "created" | "commented";
  }>;
}

/**
 * Format a detailed markdown issue body for a failed test case.
 */
function formatIssueBody(tc: CaseResult, report: RunReport): string {
  const failedSteps = tc.steps.filter((s) => s.status === "fail");

  const stepsDetails = failedSteps
    .map(
      (s) => `### ❌ Failed Step: \`${s.name}\` (\`${s.id}\`)
- **Duration**: ${s.durationMs}ms
- **Error**: \`\`\`
${s.error || "No error message provided"}
\`\`\`
${
  s.assertions.length > 0
    ? `\n**Assertions:**
${s.assertions.map((a) => `- ${a.pass ? "✅" : "❌"} ${a.message} (Expected: \`${JSON.stringify(a.expected)}\`, Actual: \`${JSON.stringify(a.actual)}\`)`).join("\n")}`
    : ""
}`
    )
    .join("\n\n");

  return `## 🚨 Automated Test Failure Report

A test case has failed during execution by **QATOOL Test Engine**.

| Property | Details |
|---|---|
| **Test Case** | \`${tc.name}\` (\`${tc.id}\`) |
| **Type** | \`${tc.type.toUpperCase()}\` |
| **Tags** | ${tc.tags.map((t) => `\`#${t}\``).join(" ") || "None"} |
| **Run ID** | \`${report.runId}\` |
| **Suite Directory** | \`${report.suiteDir}\` |
| **Execution Time** | ${new Date(report.startedAt).toISOString()} |
| **Total Attempts** | ${tc.attempts || 1} |
| **Status** | **FAILED** |

---

${stepsDetails}

---
*Auto-generated by QATOOL Platform (Phase 4 GitHub Issue Integration)*`;
}

/**
 * Sync test suite failures to GitHub Issues with smart deduplication.
 * If an open issue exists for this test, appends a run comment instead of opening a duplicate issue.
 */
export async function syncFailuresToGitHub(
  report: RunReport,
  options: GitHubIntegrationOptions = {}
): Promise<GitHubSyncResult> {
  const token = options.token || process.env.GITHUB_TOKEN;
  let owner = options.owner || process.env.GITHUB_OWNER;
  let repo = options.repo || process.env.GITHUB_REPO;

  if (repo && repo.includes("/") && !owner) {
    const [repoOwner, repoName] = repo.split("/");
    owner = repoOwner;
    repo = repoName;
  }

  if (!token || !owner || !repo) {
    console.warn("  ⚠ GitHub Issue Integration skipped: GITHUB_TOKEN or GITHUB_REPO not configured in environment.");
    return {
      totalFailures: report.failed,
      syncedCount: 0,
      createdCount: 0,
      commentedCount: 0,
      issues: [],
    };
  }

  const octokit = new Octokit({ auth: token });

  // Filter failures matching tagsFilter if provided
  let failedCases = report.cases.filter((c) => c.status === "fail");
  if (options.tagsFilter && options.tagsFilter.length > 0) {
    failedCases = failedCases.filter((c) =>
      options.tagsFilter!.some((t) => c.tags.includes(t))
    );
  }

  if (failedCases.length === 0) {
    return {
      totalFailures: 0,
      syncedCount: 0,
      createdCount: 0,
      commentedCount: 0,
      issues: [],
    };
  }

  // Fetch currently open test failure issues for deduplication
  const { data: openIssues } = await octokit.issues.listForRepo({
    owner,
    repo,
    state: "open",
    labels: "automated-test-failure",
    per_page: 100,
  });

  const syncResult: GitHubSyncResult = {
    totalFailures: failedCases.length,
    syncedCount: 0,
    createdCount: 0,
    commentedCount: 0,
    issues: [],
  };

  for (const tc of failedCases) {
    const expectedTitlePrefix = `[Test Failure] ${tc.name}`;

    // Search for existing open issue
    const existingIssue = openIssues.find(
      (issue) =>
        issue.title.includes(expectedTitlePrefix) ||
        issue.title.includes(`(${tc.id})`)
    );

    if (existingIssue) {
      // Deduplicate: Append run failure comment to the existing issue
      const commentBody = `### 🔄 Failure Recurring in Run \`${report.runId.slice(0, 8)}\`
- **Executed At**: ${new Date(report.startedAt).toISOString()}
- **Duration**: ${tc.durationMs}ms
- **Attempts**: ${tc.attempts || 1}
- **First Error**: \`${tc.steps.find((s) => s.status === "fail")?.error || "Unknown"}\`
`;
      await octokit.issues.createComment({
        owner,
        repo,
        issue_number: existingIssue.number,
        body: commentBody,
      });

      syncResult.commentedCount++;
      syncResult.syncedCount++;
      syncResult.issues.push({
        testId: tc.id,
        issueNumber: existingIssue.number,
        issueUrl: existingIssue.html_url,
        action: "commented",
      });
      console.log(`  🔗 Updated existing GitHub Issue #${existingIssue.number} for "${tc.name}"`);
    } else {
      // Create a brand new issue
      const title = `[Test Failure] ${tc.name} (${tc.id})`;
      const body = formatIssueBody(tc, report);
      const labels = ["bug", "automated-test-failure", tc.type];

      const newIssue = await octokit.issues.create({
        owner,
        repo,
        title,
        body,
        labels,
      });

      syncResult.createdCount++;
      syncResult.syncedCount++;
      syncResult.issues.push({
        testId: tc.id,
        issueNumber: newIssue.data.number,
        issueUrl: newIssue.data.html_url,
        action: "created",
      });
      console.log(`  🎯 Created new GitHub Issue #${newIssue.data.number}: "${title}"`);
    }
  }

  return syncResult;
}
